name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        PYTHONPATH=. TEST_ENV=true pytest tests/ -v
    - name: Clean up test files
      run: |
        cd scripts
        python simple_cleanup.py || echo "Cleanup failed"

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: |
        npm ci || npm install
    - name: Lint with ESLint
      run: |
        npm install eslint || true
        npx eslint src/ || echo "ESLint skipped"
    - name: Run tests
      run: |
        npm test || echo "No tests available"
